[default]
db_host = "localhost"
db_port = 5432
db_name = "geobot_db"
db_user = "alvaro_teste"

[development]
db_name = "geobot_platform"
db_user = "geobot_user"
db_password = "geobot2025"
db_port = 5433
db_host = "localhost"

[production]
db_host = "prod-db-server"
db_name = "geobot_db_prod"

