version: "3.9"

services:
  db:
    image: postgres:16
    container_name: geobot_platform_db
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: geobot_user
      POSTGRES_PASSWORD: geobot2025
      POSTGRES_DB: geobot_platform
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geobot_user -d geobot_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
